### Task 2: Dataset Practice 
1. Create student result dataset 
2. Create disease dataset 
3. Create loan approval dataset

In [2]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
import warnings
warnings.filterwarnings('ignore')

In [28]:
#student result dataset
data = {
    "Hours_Studied":[2,3,4,5,6,7,8,9,4,7],
    "Attendance":[55,60,65,70,75,80,85,90,72,88],
    "Assignments_Submitted":[3,4,5,6,7,8,9,10,6,9],
    "Result":[0,0,0,0,1,1,1,1,0,1]}
student_df = pd.DataFrame(data) 
student_df

   Hours_Studied  Attendance  Assignments_Submitted  Result
0              2          55                      3       0
1              3          60                      4       0
2              4          65                      5       0
3              5          70                      6       0
4              6          75                      7       1
5              7          80                      8       1
6              8          85                      9       1
7              9          90                     10       1
8              4          72                      6       0
9              7          88                      9       1

In [31]:
#disease dataset
data = {"Age":[25,30,35,40,45,50,55,60,42,32],
    "BMI":[21,22,24,27,29,31,33,35,28,19],
    "BP":[110,115,120,130,135,140,145,150,132,118],
    "Disease":[0,0,0,1,1,1,1,1,1,0]}
disease_df = pd.DataFrame(data)
disease_df

   Age  BMI   BP  Disease
0   25   21  110        0
1   30   22  115        0
2   35   24  120        0
3   40   27  130        1
4   45   29  135        1
5   50   31  140        1
6   55   33  145        1
7   60   35  150        1
8   42   28  132        1
9   32   19  118        0

In [35]:
#loan approval dataset
data = {'Income': [25000,30000,35000,45000,50000,60000,70000,80000,90000,100000],
    'CreditScore': [500,550,600,650,680,
                    700,720,750,780,800],
    'LoanStatus': [0, 0, 0, 1, 1, 1, 1, 1, 1, 1]}
loan_df = pd.DataFrame(data)
loan_df

   Income  CreditScore  LoanStatus
0   25000          500           0
1   30000          550           0
2   35000          600           0
3   45000          650           1
4   50000          680           1
5   60000          700           1
6   70000          720           1
7   80000          750           1
8   90000          780           1
9  100000          800           1

### Task 3: KNN Model 
1. Train KNN model 
2. Use K = 3 
3. Predict results

### Task 4: Experiment with K Values 
1. K = 1 
2. K = 3 
3. K = 5 
Compare outputs.

In [ ]:
# student dataset
#k=3
X = student_df[["Hours_Studied","Attendance","Assignments_Submitted"]]
y = student_df["Result"] 
model_s3 = KNeighborsClassifier(n_neighbors=3)
model_s3.fit(X,y)
p_1 = model_s3.predict([[7,75,8]])
print("p1:",p_1)
p_2 = model_s3.predict([[5.5,74,6.5]])
print("p2:",p_2)

p1: [1]
p2: [0]

In [26]:
#k=1
model_s1 = KNeighborsClassifier(n_neighbors=1)
model_s1.fit(X,y)
p_1 = model_s1.predict([[7,75,8]])
print("p1:",p_1)
p_2 = model_s1.predict([[5.5,74,6.5]])
print("p2:",p_2)

p1: [1]
p2: [1]

In [27]:
#k=5
model_s5 = KNeighborsClassifier(n_neighbors=5)
model_s5.fit(X,y)
p_1 = model_s5.predict([[7,75,8]])
print("p1:",p_1)
p_2 = model_s5.predict([[5.5,74,6.5]])
print("p2:",p_2)

p1: [1]
p2: [0]

##### compare outputs (students dataset)

| K | Prediction for test 1|Prediction for test 2|
| - | ----------           | ------------------- |
| 1 | Pass (1)             | Pass (1)            |
| 3 | Pass (1)             | Fail (0)            |
| 5 | Pass (1)             | Fail (0)            |

In [42]:
# disease dataset
X = disease_df[["Age","BMI","BP"]]
y = disease_df["Disease"]
model_d3 = KNeighborsClassifier(n_neighbors=3)
model_d3.fit(X,y)
p_1 = model_d3.predict([[38,25,120]])
print("p1:",p_1)
p_2 = model_d3.predict([[42,24,140]])
print("p2:",p_2)

p1: [0]
p2: [1]

In [43]:
#k=1
model_d1 = KNeighborsClassifier(n_neighbors=1)
model_d1.fit(X,y)
p_1 = model_d1.predict([[38,25,120]])
print("p1:",p_1)
p_2 = model_d1.predict([[42,24,140]])
print("p2:",p_2)

p1: [0]
p2: [1]

In [44]:
#k=5
model_d5 = KNeighborsClassifier(n_neighbors=5)
model_d5.fit(X,y)
p_1 = model_d5.predict([[38,25,120]])
print("p1:",p_1)
p_2 = model_d5.predict([[42,24,140]])
print("p2:",p_2)

p1: [0]
p2: [1]

##### compare outputs (disease dataset)

| K | Prediction for test 1|Prediction for test 2|
| - | ----------           | ------------------- |
| 1 | No disease (0)       | Disease (1)         |
| 3 | No disease (0)       | Disease (1)         |
| 5 | No disease (0)       | Disease (1)         |

In [53]:
#loan approval dataset
#k=3
X = loan_df [["Income","CreditScore"]]
y = loan_df ["LoanStatus"]
model_l3 = KNeighborsClassifier(n_neighbors=3)
model_l3.fit(X,y)
p1 = model_l3.predict([[15000,430]])
print("P1:", p1)
p2 = model_l3.predict([[40000,640]])
print("P2:",p2)

P1: [0]
P2: [1]

In [54]:
#k=5
model_l5 = KNeighborsClassifier(n_neighbors=5)
model_l5.fit(X,y)
p1 = model_l5.predict([[15000,430]])
print("P1:", p1)
p2 = model_l5.predict([[40000,640]])
print("P2:",p2)

P1: [0]
P2: [0]

In [55]:
#k=1
model_l1 = KNeighborsClassifier(n_neighbors=1)
model_l1.fit(X,y)
p1 = model_l1.predict([[15000,430]])
print("P1:", p1)
p2 = model_l1.predict([[40000, 640]])
print("P2:",p2)

P1: [0]
P2: [1]

##### compare outputs (loan approval dataset)

| K | Prediction for test 1|Prediction for test 2|
| - | ----------           | ------------------- |
| 1 | Not approved(0)      | Approved(1)     |
| 3 | Not approved(0)      | Approved(1)         |
| 5 | Not approved(0)      | Not approved(0)     |

### Task 5: Classification Practice 
Predict: 
1. Student result 
2. Disease status 
3. Customer category

In [74]:
#student result
result_1 = model_s3.predict([[4,60,7]])
print("Fail" if result_1[0] == 0 else "Pass")

Fail

In [63]:
#disease status
status = model_d3.predict([[43,25,140]])
print("Disease" if status[0]==1 else "Fail")

Disease

In [72]:
#customer category
customer_data = {"Annual_Spending": [8000,12000,15000,18000,25000,
                        30000,35000,45000,55000,65000],
    "Purchase_Frequency": [5,8,10,12,15,
                           18,20,25,30,35],
    "Category": [0,0,0,0,1,1,1,1,1,1]}

customer_df = pd.DataFrame(customer_data)

X = customer_df[["Annual_Spending","Purchase_Frequency"]]
y = customer_df["Category"]
model = KNeighborsClassifier()
model.fit(X,y)

category = model.predict([[45000,25]])
print("Premium" if category[0]==1 else "Regular")

Premium

### Task 6: Comparison Activity 
Compare: 
1. Logistic Regression 
2. KNN   and Write differences.

| Feature           | Logistic Regression | KNN            |
| ----------------- | ------------------- | -------------- |
| Model Type        | Parametric          | Non-parametric |
| Training          | Required            | Not required   |
| Prediction Speed  | Fast                | Slow           |
| Decision Boundary | Linear              | Non-linear     |
| Interpretability  | High                | Low            |
| Memory Usage      | Low                 | High           |