### Task 1: Theory 
1. What is Machine Learning? 
- Machine Learning (ML) is a branch of Artificial Intelligence that enables computers to learn from data and improve their performance without being explicitly programmed.
- ML systems identify patterns in data and use those patterns to make predictions or decisions.
- Example:
    - A music app learning your favorite songs.
    - A shopping website suggesting products you may like

---
2. Why ML is important? 
- Machine Learning is important because it helps computers:
 - Automate tasks
 - Make accurate predictions
 - Analyze large amounts of data quickly
 - Improve user experience
 - Reduce human effort
- Importance in Real Life
 - Healthcare: Disease prediction
 - Banking: Fraud detection
 - Education: Personalized learning
 - Business: Customer analysis
 - Entertainment: Movie recommendations

---

3. What is dataset? 
- A dataset is a structured collection of data used to train and evaluate ML models. It usually consists of:
 - Features (inputs): The variables or attributes used for learning.
 - Labels (outputs): The target values the model tries to predict.
- Examples (rows): Each record containing features and labels.

---
4. Difference between AI and ML 

| AI (Artificial Intelligence) | ML (Machine Learning)          |
| ---------------------------- | ------------------------------ |
| Makes machines intelligent   | Helps machines learn from data |
| Broad field                  | Subset of AI                   |
| Uses logic and rules         | Uses data and algorithms       |
| Example: Virtual assistants  | Example: Spam filter           |

---

5. Types of Machine Learning 
 1. Supervised Learning : Model learns from labeled data (e.g., predicting house prices).

 2. Unsupervised Learning : Model finds hidden patterns in unlabeled data (e.g., customer segmentation).

 3. Reinforcement Learning : Model learns by interacting with an environment and receiving rewards or penalties (e.g., training robots or game AI).

---

### Task 2: Real-World ML Examples 
1. List 5 ML applications
 - Email spam detection
 - Netflix movie recommendations
 - Face recognition in phones
 - Self-driving cars
 - Online shopping suggestions

---
2. Explain spam detection 
ML models analyze email content, sender behavior, and metadata. Features like suspicious keywords, unusual links, or sender reputation help classify emails as spam or not spam. Over time, the model adapts to new spam tactics.
3. Explain recommendation system 
These systems suggest items based on user behavior. For example, Netflix recommends shows by analyzing what you’ve watched and comparing it with similar users. Techniques include collaborative filtering (user similarity) and content-based filtering (item similarity).

---

### Task 3: Supervised Learning Practice 
1. Create student marks dataset 
2. Identify features & labels 
3. Explain prediction logic

In [1]:
# Student Marks Dataset
import pandas as pd
data = {
    "Study Hours": [2, 4, 6, 8, 10],
    "Attendance": [60, 70, 80, 90, 95],
    "Marks": [40, 55, 70, 88, 95]
}

df = pd.DataFrame(data)
print(df)

   Study Hours  Attendance  Marks
0            2          60     40
1            4          70     55
2            6          80     70
3            8          90     88
4           10          95     95

- Features (Input)
    - Study Hours
    - Attendance
- Label (Output)
    - Marks
- The ML model learns:
    - the relationship between study hours + attendance and marks
    - More study hours + better attendance = higher marks

### Task 4: Unsupervised Learning Practice 
1. Customer grouping example 
2. Pattern finding example 
3. Clustering example

In [4]:
# Customer grouping
data = {
    "Age": [18, 22, 25, 45, 50, 48],
    "Spending": [2000, 2500, 3000, 8000, 8500, 9000]
}

df = pd.DataFrame(data)
df

   Age  Spending
0   18      2000
1   22      2500
2   25      3000
3   45      8000
4   50      8500
5   48      9000

- Customers are grouped based on:
   - Age
   - Spending
- Similar customers fall into the same cluster.

In [5]:
#pattern finding
transactions = [
    ["Bread", "Butter"],
    ["Milk", "Bread"],
    ["Bread", "Butter", "Jam"],
    ["Milk", "Bread", "Butter"]
]

# Find transactions containing Bread and Butter
count = 0

for item in transactions:
    if "Bread" in item and "Butter" in item:
        count += 1

print("Bread and Butter bought together:", count, "times")

Bread and Butter bought together: 3 times

- The program finds shopping patterns.
- Customers buying Bread often buy Butter.

In [ ]:
#clustering example
data = {"R.No":[1,2,3,4,5,6,7],
    "Marks": [35, 40, 50, 65, 75, 85, 95]
}
df = pd.DataFrame(data)
df

   R.No  Marks
0     1     35
1     2     40
2     3     50
3     4     65
4     5     75
5     6     85
6     7     95

- Students are grouped into:
    - Low performers
    - Average performers
    - High performers

### Task 5: Reinforcement Learning Practice 
1. Robot learning example 
2. AI game example 
3. Reward/penalty explanation

In [7]:
# Simple Robot Reward System

position = 0

# Robot moves
moves = ["right", "right", "wrong", "right"]

reward = 0

for move in moves:

    if move == "right":
        position += 1
        reward += 10
        print("Correct Move : Reward +10")

    else:
        reward -= 5
        print("Wrong Move : Penalty -5")

print("Final Position:", position)
print("Total Reward:", reward)

Correct Move : Reward +10
Correct Move : Reward +10
Wrong Move : Penalty -5
Correct Move : Reward +10
Final Position: 3
Total Reward: 25

- Correct movement gives reward.
- Wrong movement gives penalty.
- Robot learns better actions over time.

##### Reward/penaltiy system
- Good action - Reward added
- Bad action - Penalty applied
- The agent tries to increase total rewards by choosing better actions.

In [8]:
# Simple Game AI Reward Example

game_results = ["win", "lose", "win", "win"]

score = 0

for result in game_results:

    if result == "win":
        score += 20
        print("Win → Reward +20")

    else:
        score -= 10
        print("Lose → Penalty -10")

print("Final Score:", score)

Win → Reward +20
Lose → Penalty -10
Win → Reward +20
Win → Reward +20
Final Score: 50

- The system:
    - Gets rewards for winning
    - Gets penalties for losing
- Learns strategies to maximize rewards

### Task 6: ML Workflow 
1. Draw ML workflow diagram 

Data Collection  
      ↓  
Data Cleaning  
      ↓  
Feature Selection  
      ↓  
Model Training  
      ↓  
Model Testing  
      ↓  
Prediction  
      ↓  
Deployment


2. Explain each step 

| Step              | Explanation                      |
| ----------------- | -------------------------------- |
| Data Collection   | Gather data                      |
| Data Cleaning     | Remove errors and missing values |
| Feature Selection | Choose important inputs          |
| Model Training    | Train ML algorithm               |
| Model Testing     | Check accuracy                   |
| Prediction        | Predict outputs                  |
| Deployment        | Use model in real applications   |


3. Give real-world example 
- House Price Prediction
1. Data Collection
  - Collect:
    - House size
    - Location
    - Number of rooms
2. Data Cleaning
    - Remove incorrect entries.
3. Feature Selection
    - Choose important features:
        - Area
        - Rooms
        - Location
4. Model Training
    - Train model using previous house prices.

5. Testing

    - Check prediction accuracy.

5. Prediction
    - Predict price of a new house.

6. Deployment
    - Used in real estate websites and apps.