### Task 2: Dataset Creation 
1. Create Pass/Fail dataset 
2. Create Disease dataset 
3. Create Spam dataset

In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings('ignore')

In [7]:
#Pass/Fail dataset
data = {
    "Hours_Studied":[2,3,4,5,6,7,8,9,4,7],
    "Attendance":[55,60,65,70,75,80,85,90,72,88],
    "Assignments_Submitted":[3,4,5,6,7,8,9,10,6,9],
    "Result":[0,0,0,0,1,1,1,1,0,1]}
pass_fail = pd.DataFrame(data) 
pass_fail.head(3)

   Hours_Studied  Attendance  Assignments_Submitted  Result
0              2          55                      3       0
1              3          60                      4       0
2              4          65                      5       0

In [8]:
#Disease dataset
data = {"Age":[25,30,35,40,45,50,55,60,42,32],
    "BMI":[21,22,24,27,29,31,33,35,28,19],
    "BP":[110,115,120,130,135,140,145,150,132,118],
    "Disease":[0,0,0,1,1,1,1,1,1,0]}
disease = pd.DataFrame(data)
disease.head(3)

   Age  BMI   BP  Disease
0   25   21  110        0
1   30   22  115        0
2   35   24  120        0

In [9]:
data = {"Length":[20,25,35,50,80,90,100,120,85,40],
    "Links_Count":[0,0,1,1,3,4,5,6,4,1],
    "Special_Chars":[1,2,3,4,10,12,15,18,11,3],
    "Spam":[0,0,0,0,1,1,1,1,1,0]}

spam = pd.DataFrame(data)
spam.head(3)

   Length  Links_Count  Special_Chars  Spam
0      20            0              1     0
1      25            0              2     0
2      35            1              3     0

### Task 3: Model Training 
1. Train Logistic Regression model 
2. Use fit() 
3. Predict outputs

In [16]:
# Pass/Fail dataset 
X = pass_fail[["Hours_Studied","Attendance","Assignments_Submitted"]]
y = pass_fail["Result"] 

X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2, random_state=44)
model_1 = LogisticRegression()
model_1.fit(X_train,y_train)
predictions = model_1.predict(X_test)
result = pd.DataFrame({"Actual": y_test,"Predicted": predictions}) 
print(result)
model_1.predict([[6,80,8]])

   Actual  Predicted
2       0          0
7       1          1

array([1], dtype=int64)

In [17]:
#Spam/Not Spam
X = spam[["Length","Links_Count","Special_Chars"]]
y = spam["Spam"]

X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2, random_state=44)
model_2 = LogisticRegression()
model_2.fit(X_train,y_train)
predictions = model_2.predict(X_test)
result = pd.DataFrame({"Actual": y_test,"Predicted": predictions}) 
print(result)
model_2.predict([[60,1,0]])

   Actual  Predicted
2       0          0
7       1          1

array([0], dtype=int64)

In [18]:
#disease prediction
X = disease[["Age","BMI","BP"]]
y = disease["Disease"]

X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2, random_state=44)
model_3 = LogisticRegression()
model_3.fit(X_train,y_train)
predictions = model_3.predict(X_test)
result = pd.DataFrame({"Actual": y_test,"Predicted": predictions}) 
print(result)
model_3.predict([[32,23,120]])

   Actual  Predicted
2       0          0
7       1          1

array([0], dtype=int64)

### Task 4: Prediction Practice 
1. Predict student result 
2. Predict disease status 
3. Predict spam message status

In [ ]:
#predict student result
prediction = model_1.predict([[6,55,4]])
print("Predicted:", prediction)

Predicted: [0]

In [43]:
#Predict disease status
prediction = model_3.predict([[40,25,140]])
print("Predicted:",prediction)

Predicted: [1]

In [47]:
#Predict spam message status
prediction = model_2.predict([[20,2,12]])
print("Predicted:",prediction)

Predicted: [0]

### Task 5: Probability Analysis 
1. Use predict_proba() 
2. Explain output 
3. Compare probabilities

In [52]:
student_prob = model_1.predict_proba([[6,80,8]]).round(2)
print(student_prob)

[[0.01 0.99]]

##### Explanation
- predict_proba() returns the probability for each class([Probability of Class 0, Probability of Class 1])
- Therefore:
    - 0.01 = 1% probability of Fail
    - 0.99 = 99% probability of Pass
- Hence, the student who studied 6 hours, has 80% attendance, and submitted 8 assignments is very likely to pass.

##### Compare Probabilities

| Class    | Probability |
| -----    | ----------- |
| 0  (Fail)| 0.01 (1%)   |
| 1  (Pass)| 0.99 (99%)  |

### Task 6: Classification Logic 
For each problem identify whether Logistic Regression can be used: 
1. Pass/Fail Prediction 
2. House Price Prediction 
3. Spam Detection 
4. Disease Prediction 
5. Salary Prediction

| Problem                | Logistic Regression Can Be Used? |Reason                                                                      |
| ---------------------- | -------------------------------- |----------------------------------------------------------------------------|
| Pass/Fail Prediction   | Yes                              | Output is categorical (Pass or Fail).                                      |
| House Price Prediction | No                               | Output is a continuous numeric value (price) - Linear Regression.          |
| Spam Detection         | Yes                              | Output is categorical (Spam or Not Spam).                                  |
| Disease Prediction     | Yes                              | Output is categorical (Disease or No Disease).                             |
| Salary Prediction      | No                               | Output is a continuous numeric value (salary amount) -Linear Regression.   |