### Task 1 
Create vocabulary from: 
- AI is powerful 
- AI is amazing

["AI", "is", "powerful", "amazing"]

### Task 2 
Convert: 
I love AI 
into a BoW vector manually.

vocabulary - ["I", "love", "AI"]
| I | love | AI |
| - | ---- | -- |
| 1 | 1    | 1  |


vector - [1, 1, 1]

### Task 3 
Install Scikit-Learn:

In [2]:
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\sachi\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn) (2.4.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.0-cp312-cp312-win_amd64.whl.metadata (61 kB)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\sachi\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn) (1.5.3)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.9.0-cp312-cp312-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.2 MB 2.8 MB/s eta 0:00:03
   ------ --------------------------------- 1.3/8.2 MB 3.2 MB/s eta 0:00:03
   -------- ------------------------------- 1.8/8.2 MB 2.7 MB/s eta 0:00:03
   ----------- ---------------------------- 2.4/8.2 MB 2.7 MB/s eta 0:00:03
   -------------- ------------------------- 2.9/8.2 MB 2.8 MB/s eta 0:00:02
   ----------------- ---------------------- 3.7/8.2 MB 2.8 MB/s eta 0:00:02
   -------------------- ------------------- 4.2/8.2 MB 2.9 MB/s eta 0:00:02
   ------------------------ --------------- 5.0/8.2 MB 2.9 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.2 MB 3.0 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.2 MB 2.9 MB/s eta 0:00:01
   ------------------------------ --------- 6.3/8.2 MB 2.8 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.2 MB 2.6 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.2 MB 2.6 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.2 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 2.4 MB/s  0:00:03
Downloading narwhals-2.22.1-py3-none-any.whl (454 kB)
Downloading scipy-1.18.0-cp312-cp312-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB ? eta -:--:--
    --------------------------------------- 0.8/36.6 MB 2.2 MB/s eta 0:00:16
   - -------------------------------------- 1.0/36.6 MB 2.2 MB/s eta 0:00:17
   - -------------------------------------- 1.0/36.6 MB 2.2 MB/s eta 0:00:17
   - -------------------------------------- 1.6/36.6 MB 1.4 MB/s eta 0:00:25
   -- ------------------------------------- 2.1/36.6 MB 1.6 MB/s eta 0:00:22
   -- ------------------------------------- 2.6/36.6 MB 1.7 MB/s eta 0:00:21
   --- ------------------------------------ 3.1/36.6 MB 1.8 MB/s eta 0:00:19
   ---- ----------------------------------- 3.7/36.6 MB 1.9 MB/s eta 0:00:18
   ---- ----------------------------------- 4.5/36.6 MB 2.0 MB/s eta 0:00:16
   ----- ---------------------------------- 5.0/36.6 MB 2.1 MB/s eta 0:00:16
   ------ --------------------------------- 5.8/36.6 MB 2.2 MB/s eta 0:00:14
   ------ --------------------------------- 6.3/36.6 MB 2.3 MB/s eta 0:00:14
   ------- -------------------------------- 7.1/36.6 MB 2.4 MB/s eta 0:00:13
   -------- ------------------------------- 7.6/36.6 MB 2.4 MB/s eta 0:00:13
   -------- ------------------------------- 8.1/36.6 MB 2.4 MB/s eta 0:00:12
   --------- ------------------------------ 8.7/36.6 MB 2.4 MB/s eta 0:00:12
   --------- ------------------------------ 8.9/36.6 MB 2.4 MB/s eta 0:00:12
   ---------- ----------------------------- 9.2/36.6 MB 2.3 MB/s eta 0:00:12
   ---------- ----------------------------- 9.4/36.6 MB 2.3 MB/s eta 0:00:12
   ---------- ----------------------------- 10.0/36.6 MB 2.2 MB/s eta 0:00:12
   ----------- ---------------------------- 10.2/36.6 MB 2.2 MB/s eta 0:00:12
   ----------- ---------------------------- 10.5/36.6 MB 2.2 MB/s eta 0:00:12
   ------------ --------------------------- 11.0/36.6 MB 2.2 MB/s eta 0:00:12
   ------------ --------------------------- 11.5/36.6 MB 2.2 MB/s eta 0:00:12
   ------------- -------------------------- 12.1/36.6 MB 2.2 MB/s eta 0:00:12
   ------------- -------------------------- 12.3/36.6 MB 2.2 MB/s eta 0:00:12
   -------------- ------------------------- 12.8/36.6 MB 2.2 MB/s eta 0:00:11
   -------------- ------------------------- 13.4/36.6 MB 2.2 MB/s eta 0:00:11
   --------------- ------------------------ 13.9/36.6 MB 2.2 MB/s eta 0:00:11
   ---------------- ----------------------- 14.7/36.6 MB 2.2 MB/s eta 0:00:10
   ---------------- ----------------------- 15.2/36.6 MB 2.2 MB/s eta 0:00:10
   ----------------- ---------------------- 15.7/36.6 MB 2.2 MB/s eta 0:00:10
   ----------------- ---------------------- 16.3/36.6 MB 2.3 MB/s eta 0:00:09
   ------------------ --------------------- 16.8/36.6 MB 2.3 MB/s eta 0:00:09
   ------------------- -------------------- 17.6/36.6 MB 2.3 MB/s eta 0:00:09
   -------------------- ------------------- 18.4/36.6 MB 2.3 MB/s eta 0:00:08
   -------------------- ------------------- 19.1/36.6 MB 2.4 MB/s eta 0:00:08
   --------------------- ------------------ 19.4/36.6 MB 2.4 MB/s eta 0:00:08
   --------------------- ------------------ 19.7/36.6 MB 2.3 MB/s eta 0:00:08
   ---------------------- ----------------- 20.2/36.6 MB 2.3 MB/s eta 0:00:08
   ---------------------- ----------------- 20.4/36.6 MB 2.3 MB/s eta 0:00:08
   ---------------------- ----------------- 21.0/36.6 MB 2.3 MB/s eta 0:00:07
   ----------------------- ---------------- 21.5/36.6 MB 2.3 MB/s eta 0:00:07
   ------------------------ --------------- 22.0/36.6 MB 2.3 MB/s eta 0:00:07
   ------------------------ --------------- 22.5/36.6 MB 2.3 MB/s eta 0:00:07
   ------------------------- -------------- 23.1/36.6 MB 2.3 MB/s eta 0:00:06
   ------------------------- -------------- 23.3/36.6 MB 2.3 MB/s eta 0:00:06
   -------------------------- ------------- 23.9/36.6 MB 2.3 MB/s eta 0:00:06
   -------------------------- ------------- 23.9/36.6 MB 2.3 MB/s eta 0:00:06
   -------------------------- ------------- 24.1/36.6 MB 2.2 MB/s eta 0:00:06
   --------------------------- ------------ 24.9/36.6 MB 2.2 MB/s eta 0:00:06
   --------------------------- ------------ 25.2/36.6 MB 2.2 MB/s eta 0:00:06
   ---------------------------- ----------- 26.0/36.6 MB 2.2 MB/s eta 0:00:05
   ---------------------------- ----------- 26.2/36.6 MB 2.2 MB/s eta 0:00:05
   ----------------------------- ---------- 26.7/36.6 MB 2.2 MB/s eta 0:00:05
   ------------------------------ --------- 27.5/36.6 MB 2.2 MB/s eta 0:00:05
   ------------------------------ --------- 28.3/36.6 MB 2.3 MB/s eta 0:00:04
   ------------------------------- -------- 28.8/36.6 MB 2.3 MB/s eta 0:00:04
   -------------------------------- ------- 29.4/36.6 MB 2.3 MB/s eta 0:00:04
   -------------------------------- ------- 29.9/36.6 MB 2.3 MB/s eta 0:00:03
   --------------------------------- ------ 30.4/36.6 MB 2.3 MB/s eta 0:00:03
   --------------------------------- ------ 30.7/36.6 MB 2.3 MB/s eta 0:00:03
   --------------------------------- ------ 30.7/36.6 MB 2.3 MB/s eta 0:00:03
   --------------------------------- ------ 30.9/36.6 MB 2.2 MB/s eta 0:00:03
   ---------------------------------- ----- 31.2/36.6 MB 2.2 MB/s eta 0:00:03
   ---------------------------------- ----- 31.7/36.6 MB 2.2 MB/s eta 0:00:03
   ----------------------------------- ---- 32.2/36.6 MB 2.2 MB/s eta 0:00:02
   ----------------------------------- ---- 32.5/36.6 MB 2.2 MB/s eta 0:00:02
   ------------------------------------ --- 33.0/36.6 MB 2.2 MB/s eta 0:00:02
   ------------------------------------ --- 33.8/36.6 MB 2.2 MB/s eta 0:00:02
   ------------------------------------- -- 34.3/36.6 MB 2.2 MB/s eta 0:00:02
   -------------------------------------- - 34.9/36.6 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 35.4/36.6 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  36.2/36.6 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.6 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 2.2 MB/s  0:00:16
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]

### Task 4 
Implement CountVectorizer.

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
sentences = ["I love India", " I Love my family"]
X = vectorizer.fit_transform(sentences)
print(X.toarray())

[[0 1 1 0]
 [1 0 1 1]]

In [2]:
print( vectorizer.get_feature_names_out() )

['family' 'india' 'love' 'my']

In [3]:
import pandas as pd
df = pd.DataFrame(
    X.toarray(),
    columns=vectorizer.get_feature_names_out()
)

df

   family  india  love  my
0       0      1     1   0
1       1      0     1   1

### Task 5 
Generate BoW vectors for 5 sentences.

In [4]:
sentences = [
    "The food was delicious and the service was excellent.",
    "The delivery was late but the product quality was good.",
    "I love this phone because the battery lasts all day.",
    "The laptop performance is excellent but the battery life is average.",
    "The customer support was helpful and solved my problem quickly."
]
X = vectorizer.fit_transform(sentences)
print(X.toarray())

[[0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 2 0 2]
 [0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 2 0 2]
 [1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0]
 [0 0 1 1 0 1 0 0 0 0 1 0 0 0 2 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 2 0 0]
 [0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 1 0 1]]

In [5]:
import pandas as pd
df = pd.DataFrame(
    X.toarray(),
    columns=vectorizer.get_feature_names_out()
)

df

,all,and,average,battery,because,but,customer,day,delicious,delivery,...,problem,product,quality,quickly,service,solved,support,the,this,was
0,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,2,0,2
1,0,0,0,0,0,1,0,0,0,1,...,0,1,1,0,0,0,0,2,0,2
2,1,0,0,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,1,1,0
3,0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,2,0,0
4,0,1,0,0,0,0,1,0,0,0,...,1,0,0,1,0,1,1,1,0,1